let skaicius = 3;
console.log(skaicius)
console.log(skaicius++)
console.log(skaicius)
console.log(skaicius++)
console.log(skaicius)
console.log(++skaicius)
console.log(skaicius)
console.log(skaicius--)
console.log(skaicius)
