console.log('kai saule nusileis')
console.log('ir vejas nurims')
console.log('as tave pamirsiu')
console.log('ir tu pamirsk mane')
console.log('kai saule nusileis')
console.log('ir vejas nurims')
console.log('as tave pamirsiu')
console.log('ir tu pamirsk mane')
console.log('========================')
console.log('kai saule nusileis')
console.log('========================')
console.log('ir vejas nurims')
console.log()
console.log('as tave pamirsiu')
console.log('ir tu pamirsk mane')
console.log('kai saule nusileis')
console.log('ir vejas nurims')
console.log('as tave\npamirsiu')
console.log('ir tu pamirsk mane')
console.log('kai saule nusileis')
console.log('ir vejas nurims')
console.log('\tas tave pamirsiu')
console.log('ir tu\b pamirsk mane')
